apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
  labels:
#    commit: ${WERCKER_GIT_COMMIT}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
 #       commit: ${WERCKER_GIT_COMMIT}
    spec:
      containers:
      - name: hello-world
        #image: ${DOCKER_REPO}:${WERCKER_GIT_BRANCH}-${WERCKER_GIT_COMMIT}
        image: fra.ocir.io/ptsbm02/getting-started-python:v1.0
        imagePullPolicy: Always
        ports:
        - name: hello-world
          containerPort: 5000
          protocol: TCP
      imagePullSecrets:
        - name: ptsbm02          
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
#    commit: ${WERCKER_GIT_COMMIT}
spec:
  ports:
  - port: 30000
    targetPort: 5000
  selector:
    app: hello-world
#    commit: ${WERCKER_GIT_COMMIT}
type: LoadBalancer
