apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world

spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
 
    spec:
      containers:
      - name: hello-world
        image: fra.ocir.io/ptsbm02/getting-started-python:${WERCKER_GIT_BRANCH}-${WERCKER_GIT_COMMIT}
        imagePullPolicy: Always
        ports:
        - name: hello-world
          containerPort: 5000
          protocol: TCP
          #command: ['sh','-c','pyton app.py; sleep infinity']
      imagePullSecrets:
        - name: ptsbm02          
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  ports:
  - port: 80
    targetPort: 5000
    name: hello-world-lbr
  selector:
    app: hello-world
  type: LoadBalancer
